// flow-typed signature: 48887025514a62a4834dac05dd8d370a
// flow-typed version: <<STUB>>/babel_v^6.3.26/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel/cli.js' {
  declare module.exports: $Exports<'babel/cli'>;
}
declare module 'babel/index' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/index.js' {
  declare module.exports: $Exports<'babel'>;
}
