// flow-typed signature: 09c2a7aa84e2b116423946aeea0ac2a8
// flow-typed version: <<STUB>>/base16_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base16'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'base16' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base16/lib/apathy' {
  declare module.exports: any;
}

declare module 'base16/lib/ashes' {
  declare module.exports: any;
}

declare module 'base16/lib/atelier-dune' {
  declare module.exports: any;
}

declare module 'base16/lib/atelier-forest' {
  declare module.exports: any;
}

declare module 'base16/lib/atelier-heath' {
  declare module.exports: any;
}

declare module 'base16/lib/atelier-lakeside' {
  declare module.exports: any;
}

declare module 'base16/lib/atelier-seaside' {
  declare module.exports: any;
}

declare module 'base16/lib/bespin' {
  declare module.exports: any;
}

declare module 'base16/lib/brewer' {
  declare module.exports: any;
}

declare module 'base16/lib/bright' {
  declare module.exports: any;
}

declare module 'base16/lib/chalk' {
  declare module.exports: any;
}

declare module 'base16/lib/codeschool' {
  declare module.exports: any;
}

declare module 'base16/lib/colors' {
  declare module.exports: any;
}

declare module 'base16/lib/default' {
  declare module.exports: any;
}

declare module 'base16/lib/eighties' {
  declare module.exports: any;
}

declare module 'base16/lib/embers' {
  declare module.exports: any;
}

declare module 'base16/lib/flat' {
  declare module.exports: any;
}

declare module 'base16/lib/google' {
  declare module.exports: any;
}

declare module 'base16/lib/grayscale' {
  declare module.exports: any;
}

declare module 'base16/lib/greenscreen' {
  declare module.exports: any;
}

declare module 'base16/lib/harmonic' {
  declare module.exports: any;
}

declare module 'base16/lib/hopscotch' {
  declare module.exports: any;
}

declare module 'base16/lib/index' {
  declare module.exports: any;
}

declare module 'base16/lib/isotope' {
  declare module.exports: any;
}

declare module 'base16/lib/marrakesh' {
  declare module.exports: any;
}

declare module 'base16/lib/mocha' {
  declare module.exports: any;
}

declare module 'base16/lib/monokai' {
  declare module.exports: any;
}

declare module 'base16/lib/ocean' {
  declare module.exports: any;
}

declare module 'base16/lib/paraiso' {
  declare module.exports: any;
}

declare module 'base16/lib/pop' {
  declare module.exports: any;
}

declare module 'base16/lib/railscasts' {
  declare module.exports: any;
}

declare module 'base16/lib/shapeshifter' {
  declare module.exports: any;
}

declare module 'base16/lib/solarized' {
  declare module.exports: any;
}

declare module 'base16/lib/summerfruit' {
  declare module.exports: any;
}

declare module 'base16/lib/threezerotwofour' {
  declare module.exports: any;
}

declare module 'base16/lib/tomorrow' {
  declare module.exports: any;
}

declare module 'base16/lib/tube' {
  declare module.exports: any;
}

declare module 'base16/lib/twilight' {
  declare module.exports: any;
}

declare module 'base16/src/apathy' {
  declare module.exports: any;
}

declare module 'base16/src/ashes' {
  declare module.exports: any;
}

declare module 'base16/src/atelier-dune' {
  declare module.exports: any;
}

declare module 'base16/src/atelier-forest' {
  declare module.exports: any;
}

declare module 'base16/src/atelier-heath' {
  declare module.exports: any;
}

declare module 'base16/src/atelier-lakeside' {
  declare module.exports: any;
}

declare module 'base16/src/atelier-seaside' {
  declare module.exports: any;
}

declare module 'base16/src/bespin' {
  declare module.exports: any;
}

declare module 'base16/src/brewer' {
  declare module.exports: any;
}

declare module 'base16/src/bright' {
  declare module.exports: any;
}

declare module 'base16/src/chalk' {
  declare module.exports: any;
}

declare module 'base16/src/codeschool' {
  declare module.exports: any;
}

declare module 'base16/src/colors' {
  declare module.exports: any;
}

declare module 'base16/src/default' {
  declare module.exports: any;
}

declare module 'base16/src/eighties' {
  declare module.exports: any;
}

declare module 'base16/src/embers' {
  declare module.exports: any;
}

declare module 'base16/src/flat' {
  declare module.exports: any;
}

declare module 'base16/src/google' {
  declare module.exports: any;
}

declare module 'base16/src/grayscale' {
  declare module.exports: any;
}

declare module 'base16/src/greenscreen' {
  declare module.exports: any;
}

declare module 'base16/src/harmonic' {
  declare module.exports: any;
}

declare module 'base16/src/hopscotch' {
  declare module.exports: any;
}

declare module 'base16/src/index' {
  declare module.exports: any;
}

declare module 'base16/src/isotope' {
  declare module.exports: any;
}

declare module 'base16/src/marrakesh' {
  declare module.exports: any;
}

declare module 'base16/src/mocha' {
  declare module.exports: any;
}

declare module 'base16/src/monokai' {
  declare module.exports: any;
}

declare module 'base16/src/ocean' {
  declare module.exports: any;
}

declare module 'base16/src/paraiso' {
  declare module.exports: any;
}

declare module 'base16/src/pop' {
  declare module.exports: any;
}

declare module 'base16/src/railscasts' {
  declare module.exports: any;
}

declare module 'base16/src/shapeshifter' {
  declare module.exports: any;
}

declare module 'base16/src/solarized' {
  declare module.exports: any;
}

declare module 'base16/src/summerfruit' {
  declare module.exports: any;
}

declare module 'base16/src/threezerotwofour' {
  declare module.exports: any;
}

declare module 'base16/src/tomorrow' {
  declare module.exports: any;
}

declare module 'base16/src/tube' {
  declare module.exports: any;
}

declare module 'base16/src/twilight' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base16/lib/apathy.js' {
  declare module.exports: $Exports<'base16/lib/apathy'>;
}
declare module 'base16/lib/ashes.js' {
  declare module.exports: $Exports<'base16/lib/ashes'>;
}
declare module 'base16/lib/atelier-dune.js' {
  declare module.exports: $Exports<'base16/lib/atelier-dune'>;
}
declare module 'base16/lib/atelier-forest.js' {
  declare module.exports: $Exports<'base16/lib/atelier-forest'>;
}
declare module 'base16/lib/atelier-heath.js' {
  declare module.exports: $Exports<'base16/lib/atelier-heath'>;
}
declare module 'base16/lib/atelier-lakeside.js' {
  declare module.exports: $Exports<'base16/lib/atelier-lakeside'>;
}
declare module 'base16/lib/atelier-seaside.js' {
  declare module.exports: $Exports<'base16/lib/atelier-seaside'>;
}
declare module 'base16/lib/bespin.js' {
  declare module.exports: $Exports<'base16/lib/bespin'>;
}
declare module 'base16/lib/brewer.js' {
  declare module.exports: $Exports<'base16/lib/brewer'>;
}
declare module 'base16/lib/bright.js' {
  declare module.exports: $Exports<'base16/lib/bright'>;
}
declare module 'base16/lib/chalk.js' {
  declare module.exports: $Exports<'base16/lib/chalk'>;
}
declare module 'base16/lib/codeschool.js' {
  declare module.exports: $Exports<'base16/lib/codeschool'>;
}
declare module 'base16/lib/colors.js' {
  declare module.exports: $Exports<'base16/lib/colors'>;
}
declare module 'base16/lib/default.js' {
  declare module.exports: $Exports<'base16/lib/default'>;
}
declare module 'base16/lib/eighties.js' {
  declare module.exports: $Exports<'base16/lib/eighties'>;
}
declare module 'base16/lib/embers.js' {
  declare module.exports: $Exports<'base16/lib/embers'>;
}
declare module 'base16/lib/flat.js' {
  declare module.exports: $Exports<'base16/lib/flat'>;
}
declare module 'base16/lib/google.js' {
  declare module.exports: $Exports<'base16/lib/google'>;
}
declare module 'base16/lib/grayscale.js' {
  declare module.exports: $Exports<'base16/lib/grayscale'>;
}
declare module 'base16/lib/greenscreen.js' {
  declare module.exports: $Exports<'base16/lib/greenscreen'>;
}
declare module 'base16/lib/harmonic.js' {
  declare module.exports: $Exports<'base16/lib/harmonic'>;
}
declare module 'base16/lib/hopscotch.js' {
  declare module.exports: $Exports<'base16/lib/hopscotch'>;
}
declare module 'base16/lib/index.js' {
  declare module.exports: $Exports<'base16/lib/index'>;
}
declare module 'base16/lib/isotope.js' {
  declare module.exports: $Exports<'base16/lib/isotope'>;
}
declare module 'base16/lib/marrakesh.js' {
  declare module.exports: $Exports<'base16/lib/marrakesh'>;
}
declare module 'base16/lib/mocha.js' {
  declare module.exports: $Exports<'base16/lib/mocha'>;
}
declare module 'base16/lib/monokai.js' {
  declare module.exports: $Exports<'base16/lib/monokai'>;
}
declare module 'base16/lib/ocean.js' {
  declare module.exports: $Exports<'base16/lib/ocean'>;
}
declare module 'base16/lib/paraiso.js' {
  declare module.exports: $Exports<'base16/lib/paraiso'>;
}
declare module 'base16/lib/pop.js' {
  declare module.exports: $Exports<'base16/lib/pop'>;
}
declare module 'base16/lib/railscasts.js' {
  declare module.exports: $Exports<'base16/lib/railscasts'>;
}
declare module 'base16/lib/shapeshifter.js' {
  declare module.exports: $Exports<'base16/lib/shapeshifter'>;
}
declare module 'base16/lib/solarized.js' {
  declare module.exports: $Exports<'base16/lib/solarized'>;
}
declare module 'base16/lib/summerfruit.js' {
  declare module.exports: $Exports<'base16/lib/summerfruit'>;
}
declare module 'base16/lib/threezerotwofour.js' {
  declare module.exports: $Exports<'base16/lib/threezerotwofour'>;
}
declare module 'base16/lib/tomorrow.js' {
  declare module.exports: $Exports<'base16/lib/tomorrow'>;
}
declare module 'base16/lib/tube.js' {
  declare module.exports: $Exports<'base16/lib/tube'>;
}
declare module 'base16/lib/twilight.js' {
  declare module.exports: $Exports<'base16/lib/twilight'>;
}
declare module 'base16/src/apathy.js' {
  declare module.exports: $Exports<'base16/src/apathy'>;
}
declare module 'base16/src/ashes.js' {
  declare module.exports: $Exports<'base16/src/ashes'>;
}
declare module 'base16/src/atelier-dune.js' {
  declare module.exports: $Exports<'base16/src/atelier-dune'>;
}
declare module 'base16/src/atelier-forest.js' {
  declare module.exports: $Exports<'base16/src/atelier-forest'>;
}
declare module 'base16/src/atelier-heath.js' {
  declare module.exports: $Exports<'base16/src/atelier-heath'>;
}
declare module 'base16/src/atelier-lakeside.js' {
  declare module.exports: $Exports<'base16/src/atelier-lakeside'>;
}
declare module 'base16/src/atelier-seaside.js' {
  declare module.exports: $Exports<'base16/src/atelier-seaside'>;
}
declare module 'base16/src/bespin.js' {
  declare module.exports: $Exports<'base16/src/bespin'>;
}
declare module 'base16/src/brewer.js' {
  declare module.exports: $Exports<'base16/src/brewer'>;
}
declare module 'base16/src/bright.js' {
  declare module.exports: $Exports<'base16/src/bright'>;
}
declare module 'base16/src/chalk.js' {
  declare module.exports: $Exports<'base16/src/chalk'>;
}
declare module 'base16/src/codeschool.js' {
  declare module.exports: $Exports<'base16/src/codeschool'>;
}
declare module 'base16/src/colors.js' {
  declare module.exports: $Exports<'base16/src/colors'>;
}
declare module 'base16/src/default.js' {
  declare module.exports: $Exports<'base16/src/default'>;
}
declare module 'base16/src/eighties.js' {
  declare module.exports: $Exports<'base16/src/eighties'>;
}
declare module 'base16/src/embers.js' {
  declare module.exports: $Exports<'base16/src/embers'>;
}
declare module 'base16/src/flat.js' {
  declare module.exports: $Exports<'base16/src/flat'>;
}
declare module 'base16/src/google.js' {
  declare module.exports: $Exports<'base16/src/google'>;
}
declare module 'base16/src/grayscale.js' {
  declare module.exports: $Exports<'base16/src/grayscale'>;
}
declare module 'base16/src/greenscreen.js' {
  declare module.exports: $Exports<'base16/src/greenscreen'>;
}
declare module 'base16/src/harmonic.js' {
  declare module.exports: $Exports<'base16/src/harmonic'>;
}
declare module 'base16/src/hopscotch.js' {
  declare module.exports: $Exports<'base16/src/hopscotch'>;
}
declare module 'base16/src/index.js' {
  declare module.exports: $Exports<'base16/src/index'>;
}
declare module 'base16/src/isotope.js' {
  declare module.exports: $Exports<'base16/src/isotope'>;
}
declare module 'base16/src/marrakesh.js' {
  declare module.exports: $Exports<'base16/src/marrakesh'>;
}
declare module 'base16/src/mocha.js' {
  declare module.exports: $Exports<'base16/src/mocha'>;
}
declare module 'base16/src/monokai.js' {
  declare module.exports: $Exports<'base16/src/monokai'>;
}
declare module 'base16/src/ocean.js' {
  declare module.exports: $Exports<'base16/src/ocean'>;
}
declare module 'base16/src/paraiso.js' {
  declare module.exports: $Exports<'base16/src/paraiso'>;
}
declare module 'base16/src/pop.js' {
  declare module.exports: $Exports<'base16/src/pop'>;
}
declare module 'base16/src/railscasts.js' {
  declare module.exports: $Exports<'base16/src/railscasts'>;
}
declare module 'base16/src/shapeshifter.js' {
  declare module.exports: $Exports<'base16/src/shapeshifter'>;
}
declare module 'base16/src/solarized.js' {
  declare module.exports: $Exports<'base16/src/solarized'>;
}
declare module 'base16/src/summerfruit.js' {
  declare module.exports: $Exports<'base16/src/summerfruit'>;
}
declare module 'base16/src/threezerotwofour.js' {
  declare module.exports: $Exports<'base16/src/threezerotwofour'>;
}
declare module 'base16/src/tomorrow.js' {
  declare module.exports: $Exports<'base16/src/tomorrow'>;
}
declare module 'base16/src/tube.js' {
  declare module.exports: $Exports<'base16/src/tube'>;
}
declare module 'base16/src/twilight.js' {
  declare module.exports: $Exports<'base16/src/twilight'>;
}
