// flow-typed signature: aedb785a7da9e1f2ecdf25aa3c75cdda
// flow-typed version: <<STUB>>/dateformat_v^1.0.12/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dateformat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dateformat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dateformat/bin/cli' {
  declare module.exports: any;
}

declare module 'dateformat/lib/dateformat' {
  declare module.exports: any;
}

declare module 'dateformat/test/test_dayofweek' {
  declare module.exports: any;
}

declare module 'dateformat/test/test_formats' {
  declare module.exports: any;
}

declare module 'dateformat/test/test_isoutcdatetime' {
  declare module.exports: any;
}

declare module 'dateformat/test/weekofyear/test_weekofyear' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dateformat/bin/cli.js' {
  declare module.exports: $Exports<'dateformat/bin/cli'>;
}
declare module 'dateformat/lib/dateformat.js' {
  declare module.exports: $Exports<'dateformat/lib/dateformat'>;
}
declare module 'dateformat/test/test_dayofweek.js' {
  declare module.exports: $Exports<'dateformat/test/test_dayofweek'>;
}
declare module 'dateformat/test/test_formats.js' {
  declare module.exports: $Exports<'dateformat/test/test_formats'>;
}
declare module 'dateformat/test/test_isoutcdatetime.js' {
  declare module.exports: $Exports<'dateformat/test/test_isoutcdatetime'>;
}
declare module 'dateformat/test/weekofyear/test_weekofyear.js' {
  declare module.exports: $Exports<'dateformat/test/weekofyear/test_weekofyear'>;
}
