// flow-typed signature: c807472b6041027d3c6a9f99819b8804
// flow-typed version: <<STUB>>/export-files-webpack-plugin_v0.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'export-files-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'export-files-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'export-files-webpack-plugin/index' {
  declare module.exports: $Exports<'export-files-webpack-plugin'>;
}
declare module 'export-files-webpack-plugin/index.js' {
  declare module.exports: $Exports<'export-files-webpack-plugin'>;
}
