// flow-typed signature: d85e1f068e3a1b3fe19183ed065deaa3
// flow-typed version: <<STUB>>/git-directory-deploy_v^1.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-directory-deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-directory-deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-directory-deploy/cliArgs' {
  declare module.exports: any;
}

declare module 'git-directory-deploy/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-directory-deploy/cliArgs.js' {
  declare module.exports: $Exports<'git-directory-deploy/cliArgs'>;
}
declare module 'git-directory-deploy/index' {
  declare module.exports: $Exports<'git-directory-deploy'>;
}
declare module 'git-directory-deploy/index.js' {
  declare module.exports: $Exports<'git-directory-deploy'>;
}
declare module 'git-directory-deploy/test/index.js' {
  declare module.exports: $Exports<'git-directory-deploy/test/index'>;
}
