// flow-typed signature: bd581ef5152539f48f4be82ce9351b6f
// flow-typed version: <<STUB>>/javascript-stringify_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-stringify/javascript-stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-stringify/javascript-stringify.js' {
  declare module.exports: $Exports<'javascript-stringify/javascript-stringify'>;
}
