// flow-typed signature: c8b77decaf8bba7bd49d833fc7edc0ec
// flow-typed version: <<STUB>>/jss-nested_v^3.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-nested'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-nested' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-nested/benchmark/tests/bootstrap' {
  declare module.exports: any;
}

declare module 'jss-nested/benchmark/tests/deep-nesting' {
  declare module.exports: any;
}

declare module 'jss-nested/dist/jss-nested' {
  declare module.exports: any;
}

declare module 'jss-nested/dist/jss-nested.min' {
  declare module.exports: any;
}

declare module 'jss-nested/karma.conf' {
  declare module.exports: any;
}

declare module 'jss-nested/lib/index' {
  declare module.exports: any;
}

declare module 'jss-nested/lib/index.test' {
  declare module.exports: any;
}

declare module 'jss-nested/tests.webpack' {
  declare module.exports: any;
}

declare module 'jss-nested/tests/index' {
  declare module.exports: any;
}

declare module 'jss-nested/tests/index.test' {
  declare module.exports: any;
}

declare module 'jss-nested/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-nested/benchmark/tests/bootstrap.js' {
  declare module.exports: $Exports<'jss-nested/benchmark/tests/bootstrap'>;
}
declare module 'jss-nested/benchmark/tests/deep-nesting.js' {
  declare module.exports: $Exports<'jss-nested/benchmark/tests/deep-nesting'>;
}
declare module 'jss-nested/dist/jss-nested.js' {
  declare module.exports: $Exports<'jss-nested/dist/jss-nested'>;
}
declare module 'jss-nested/dist/jss-nested.min.js' {
  declare module.exports: $Exports<'jss-nested/dist/jss-nested.min'>;
}
declare module 'jss-nested/karma.conf.js' {
  declare module.exports: $Exports<'jss-nested/karma.conf'>;
}
declare module 'jss-nested/lib/index.js' {
  declare module.exports: $Exports<'jss-nested/lib/index'>;
}
declare module 'jss-nested/lib/index.test.js' {
  declare module.exports: $Exports<'jss-nested/lib/index.test'>;
}
declare module 'jss-nested/tests.webpack.js' {
  declare module.exports: $Exports<'jss-nested/tests.webpack'>;
}
declare module 'jss-nested/tests/index.js' {
  declare module.exports: $Exports<'jss-nested/tests/index'>;
}
declare module 'jss-nested/tests/index.test.js' {
  declare module.exports: $Exports<'jss-nested/tests/index.test'>;
}
declare module 'jss-nested/webpack.config.js' {
  declare module.exports: $Exports<'jss-nested/webpack.config'>;
}
