// flow-typed signature: 2771909add299d14d44623381b3b1abc
// flow-typed version: <<STUB>>/jss-vendor-prefixer_v^4.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-vendor-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-vendor-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-vendor-prefixer/dist/jss-vendor-prefixer' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/dist/jss-vendor-prefixer.min' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/karma.conf' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/lib/index' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/lib/index.test' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/tests.webpack' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/tests/index' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/tests/index.test' {
  declare module.exports: any;
}

declare module 'jss-vendor-prefixer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-vendor-prefixer/dist/jss-vendor-prefixer.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/dist/jss-vendor-prefixer'>;
}
declare module 'jss-vendor-prefixer/dist/jss-vendor-prefixer.min.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/dist/jss-vendor-prefixer.min'>;
}
declare module 'jss-vendor-prefixer/karma.conf.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/karma.conf'>;
}
declare module 'jss-vendor-prefixer/lib/index.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/lib/index'>;
}
declare module 'jss-vendor-prefixer/lib/index.test.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/lib/index.test'>;
}
declare module 'jss-vendor-prefixer/tests.webpack.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/tests.webpack'>;
}
declare module 'jss-vendor-prefixer/tests/index.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/tests/index'>;
}
declare module 'jss-vendor-prefixer/tests/index.test.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/tests/index.test'>;
}
declare module 'jss-vendor-prefixer/webpack.config.js' {
  declare module.exports: $Exports<'jss-vendor-prefixer/webpack.config'>;
}
