// flow-typed signature: a8525dbe8469d67a9bd98b7611d61384
// flow-typed version: <<STUB>>/jss_v^6.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss/dist/jss' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.min' {
  declare module.exports: any;
}

declare module 'jss/karma.conf' {
  declare module.exports: any;
}

declare module 'jss/lib/backends/DomRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/backends/VirtualRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/createRule' {
  declare module.exports: any;
}

declare module 'jss/lib/findRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/index' {
  declare module.exports: any;
}

declare module 'jss/lib/Jss' {
  declare module.exports: any;
}

declare module 'jss/lib/PluginsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/ConditionalRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/FontFaceRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/KeyframeRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/Rule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/SimpleRule' {
  declare module.exports: any;
}

declare module 'jss/lib/RulesContainer' {
  declare module.exports: any;
}

declare module 'jss/lib/SheetsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/StyleSheet' {
  declare module.exports: any;
}

declare module 'jss/lib/utils' {
  declare module.exports: any;
}

declare module 'jss/tests.webpack' {
  declare module.exports: any;
}

declare module 'jss/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss/dist/jss.js' {
  declare module.exports: $Exports<'jss/dist/jss'>;
}
declare module 'jss/dist/jss.min.js' {
  declare module.exports: $Exports<'jss/dist/jss.min'>;
}
declare module 'jss/karma.conf.js' {
  declare module.exports: $Exports<'jss/karma.conf'>;
}
declare module 'jss/lib/backends/DomRenderer.js' {
  declare module.exports: $Exports<'jss/lib/backends/DomRenderer'>;
}
declare module 'jss/lib/backends/VirtualRenderer.js' {
  declare module.exports: $Exports<'jss/lib/backends/VirtualRenderer'>;
}
declare module 'jss/lib/createRule.js' {
  declare module.exports: $Exports<'jss/lib/createRule'>;
}
declare module 'jss/lib/findRenderer.js' {
  declare module.exports: $Exports<'jss/lib/findRenderer'>;
}
declare module 'jss/lib/index.js' {
  declare module.exports: $Exports<'jss/lib/index'>;
}
declare module 'jss/lib/Jss.js' {
  declare module.exports: $Exports<'jss/lib/Jss'>;
}
declare module 'jss/lib/PluginsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/PluginsRegistry'>;
}
declare module 'jss/lib/rules/ConditionalRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/ConditionalRule'>;
}
declare module 'jss/lib/rules/FontFaceRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/FontFaceRule'>;
}
declare module 'jss/lib/rules/KeyframeRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/KeyframeRule'>;
}
declare module 'jss/lib/rules/Rule.js' {
  declare module.exports: $Exports<'jss/lib/rules/Rule'>;
}
declare module 'jss/lib/rules/SimpleRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/SimpleRule'>;
}
declare module 'jss/lib/RulesContainer.js' {
  declare module.exports: $Exports<'jss/lib/RulesContainer'>;
}
declare module 'jss/lib/SheetsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/SheetsRegistry'>;
}
declare module 'jss/lib/StyleSheet.js' {
  declare module.exports: $Exports<'jss/lib/StyleSheet'>;
}
declare module 'jss/lib/utils.js' {
  declare module.exports: $Exports<'jss/lib/utils'>;
}
declare module 'jss/tests.webpack.js' {
  declare module.exports: $Exports<'jss/tests.webpack'>;
}
declare module 'jss/webpack.config.js' {
  declare module.exports: $Exports<'jss/webpack.config'>;
}
