// flow-typed signature: 1008f2ef17afcb362a7c1c2d677cf70e
// flow-typed version: <<STUB>>/lodash.shuffle_v^4.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.shuffle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.shuffle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.shuffle/index' {
  declare module.exports: $Exports<'lodash.shuffle'>;
}
declare module 'lodash.shuffle/index.js' {
  declare module.exports: $Exports<'lodash.shuffle'>;
}
