// flow-typed signature: 69c958e92ef7ea20d332a6eafc9be1ba
// flow-typed version: <<STUB>>/react-input-enhancements_v^0.5.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-enhancements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-enhancements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-enhancements/lib/applyMaskToString' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/Autosize' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/Combobox' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/createStyling' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/DatePicker' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/DropdownOption' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/filters/filterByMatchingTextWithThreshold' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/filters/filterRedudantSeparators' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/filters/index' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/filters/limitBy' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/filters/notFoundMessage' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/filters/sortByMatchingText' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/index' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/InputPopup' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/Mask' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/shapes' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/themes/default' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/deprecated' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/findMatchingTextIndex' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/getComputedStyle' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/getInput' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/getOptionLabel' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/getOptionText' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/getOptionValue' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/isStatic' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/registerInput' {
  declare module.exports: any;
}

declare module 'react-input-enhancements/lib/utils/renderChild' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-enhancements/lib/applyMaskToString.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/applyMaskToString'>;
}
declare module 'react-input-enhancements/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/Autocomplete'>;
}
declare module 'react-input-enhancements/lib/Autosize.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/Autosize'>;
}
declare module 'react-input-enhancements/lib/Combobox.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/Combobox'>;
}
declare module 'react-input-enhancements/lib/createStyling.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/createStyling'>;
}
declare module 'react-input-enhancements/lib/DatePicker.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/DatePicker'>;
}
declare module 'react-input-enhancements/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/Dropdown'>;
}
declare module 'react-input-enhancements/lib/DropdownOption.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/DropdownOption'>;
}
declare module 'react-input-enhancements/lib/filters/filterByMatchingTextWithThreshold.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/filters/filterByMatchingTextWithThreshold'>;
}
declare module 'react-input-enhancements/lib/filters/filterRedudantSeparators.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/filters/filterRedudantSeparators'>;
}
declare module 'react-input-enhancements/lib/filters/index.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/filters/index'>;
}
declare module 'react-input-enhancements/lib/filters/limitBy.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/filters/limitBy'>;
}
declare module 'react-input-enhancements/lib/filters/notFoundMessage.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/filters/notFoundMessage'>;
}
declare module 'react-input-enhancements/lib/filters/sortByMatchingText.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/filters/sortByMatchingText'>;
}
declare module 'react-input-enhancements/lib/index.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/index'>;
}
declare module 'react-input-enhancements/lib/InputPopup.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/InputPopup'>;
}
declare module 'react-input-enhancements/lib/Mask.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/Mask'>;
}
declare module 'react-input-enhancements/lib/shapes.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/shapes'>;
}
declare module 'react-input-enhancements/lib/themes/default.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/themes/default'>;
}
declare module 'react-input-enhancements/lib/utils/deprecated.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/deprecated'>;
}
declare module 'react-input-enhancements/lib/utils/findMatchingTextIndex.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/findMatchingTextIndex'>;
}
declare module 'react-input-enhancements/lib/utils/getComputedStyle.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/getComputedStyle'>;
}
declare module 'react-input-enhancements/lib/utils/getInput.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/getInput'>;
}
declare module 'react-input-enhancements/lib/utils/getOptionLabel.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/getOptionLabel'>;
}
declare module 'react-input-enhancements/lib/utils/getOptionText.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/getOptionText'>;
}
declare module 'react-input-enhancements/lib/utils/getOptionValue.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/getOptionValue'>;
}
declare module 'react-input-enhancements/lib/utils/isStatic.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/isStatic'>;
}
declare module 'react-input-enhancements/lib/utils/registerInput.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/registerInput'>;
}
declare module 'react-input-enhancements/lib/utils/renderChild.js' {
  declare module.exports: $Exports<'react-input-enhancements/lib/utils/renderChild'>;
}
