// flow-typed signature: db8399d20300f4347ca424bce2d3cc9f
// flow-typed version: <<STUB>>/redux-devtools-themes_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-themes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-themes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-themes/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-themes/lib/nicinabox' {
  declare module.exports: any;
}

declare module 'redux-devtools-themes/src/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-themes/src/nicinabox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-themes/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-themes/lib/index'>;
}
declare module 'redux-devtools-themes/lib/nicinabox.js' {
  declare module.exports: $Exports<'redux-devtools-themes/lib/nicinabox'>;
}
declare module 'redux-devtools-themes/src/index.js' {
  declare module.exports: $Exports<'redux-devtools-themes/src/index'>;
}
declare module 'redux-devtools-themes/src/nicinabox.js' {
  declare module.exports: $Exports<'redux-devtools-themes/src/nicinabox'>;
}
